### ISSUE TITLE
lines are not linking to circles

### ISSUE THREAD

**Issue by tonmanayo** [dadalar/DDSpiderChart#2]
hey, thank you for the cool library, for some reason the lines that go from the centre of the circle to the headings aren't connecting.

tested it with many different amounts of heading and same problem 

works correctly once I set the values of the circle count to 4 and circle gap to 30

only tested on iphone 8 plus

**Comment by dadalar** [comment]
@tonmanayo thanks for the feedback. Can you provide a screenshot or some code were I can reproduce this issue?

**Comment by tonmanayo** [comment]
![screen shot 2017-11-08 at 8 44 04 pm](https://user-images.githubusercontent.com/18025339/32568054-cdb90186-c4c5-11e7-8b63-2ee76b3c5d5c.png)

This is how I create it:

 lazy var spiderChartView:DDSpiderChartView = {
        let chart = DDSpiderChartView(frame: self.frame)
        chart.circleCount = 4
        chart.circleGap = 30
        chart.backgroundColor = .white   
        chart.translatesAutoresizingMaskIntoConstraints = false
        return chart
    }()


This is how I place it:

 spiderChartView.centerXAnchor.constraint(equalTo: self.centerXAnchor).isActive = true
 spiderChartView.centerYAnchor.constraint(equalTo: self.centerYAnchor).isActive = true
 spiderChartView.heightAnchor.constraint(equalTo: self.widthAnchor).isActive = true
 spiderChartView.widthAnchor.constraint(equalTo: self.widthAnchor).isActive = true

**Comment by tonmanayo** [comment]
update: I think its a problem on my side to do when I update the constraints, when I change the orientation it sometimes fixes it's self. you're welcome to check my project 
https://github.com/janhoon/Swifty_Companion

I'm the only one working on it but it's not on my repo

**Comment by dadalar** [comment]
@tonmanayo Good catch, there was indeed a bug on calculations! I've now pushed a new version of the library (0.3). If you can do a `pod update`, you should be fine.
